### ISSUE TITLE
[Enhancement] Enable the calculator to be controlled using a keyboard

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/PyDataMath-II#3]
I thought it would be kinda nice to use the keypad on my keyboard to enter stuff.  Since you did your keys the "right way", all it required was adding a single parameter to your window call, `return_keyboard_events`:

```python
window = sg.Window('PyDataMath-II', layout=layout, background_color="#272533", size=(580, 660), return_keyboard_events=True)
```

Give it a try... it just works!

I also see you write a version in tkinter too.  I'm surprised at how compact you are able to make your tkinter code.  It doesn't look much like the tkinter code I'm used to running into.  You're quite efficient.

The lines of code are pretty code too.  I think this parameter adds a little cherry on top of the PSG version 😏

**Comment by israel-dryer** [comment]
That's a great recommendation. I added it. Also use the `bind_return_key` on the equals button.
I can clear with SHIFT+C, but what would be a good way of tying the 'escape' key to the 'C' button. Or is that possible without too much complication?

**Comment by israel-dryer** [comment]
Not sure if you saw [this version](https://github.com/israel-dryer/PyDataMath). It's a legacy calculator with a transparent background with clickable buttons. I cropped the buttons from the original photo and used them as images on the TKinter buttons so that it is as close to using the original as possible on a computer.

**Comment by PySimpleGUI** [comment]
Shift is a separate key.  Escape won't be a problem.   I recommend simply placing a print after the read to see what's being returned.

BTW, please send me an email if you have the opportunity.

**Comment by israel-dryer** [comment]
do you have your email address posted somewhere? I didn't see it?

**Comment by PySimpleGUI** [comment]
help@PySimpleGUI.org will make it to me

**Comment by israel-dryer** [comment]
works perfect... thanks for the tip. Not sure why I didn't think of printing the events.
![image](https://user-images.githubusercontent.com/42584742/65098689-38ee3300-d995-11e9-977d-e7b36ff18813.png)

**Comment by PySimpleGUI** [comment]
There ya go!!
You're great at illustrating BTW.  Even simple stuff like this.

**Comment by israel-dryer** [comment]
Oh thanks. I have to make up for in creativity what I lack in raw cognitive horsepower. haha. I try to find ways to make it as clean and simple as possible so that even I can understand it.
